#!/usr/bin/env node
/* tools/paysync.mjs: THE PAYMENT RAILS THE ORDER PAGE MAY OFFER, generated from the pay master.
 *
 * A customer who has been told his order is ready picks how he will pay, and the page hands him
 * ONE link into QR Command (Code\qr-command), the read-only site that draws the codes and copies
 * the account numbers. Which accounts exist, what each is called and which rails each carries
 * are decided in the pay store (Code\qr-command\data\accounts.json) and nowhere else, so this
 * file reads that record and writes stmt/pay.js from it, the way tools/stmt-style.mjs writes
 * stmt/statement-css.js: one source, a generated copy where the source cannot reach, and the
 * suite holding the two together whenever the master is on the machine.
 *
 * WHAT SHIPS IS THE NAME AND THE RAILS, AND NOTHING THAT PAYS. No account number, no payload,
 * no biller reference, no member number, no owner, no colour. The statements site is a second
 * Worker that holds nothing but ciphertext and a verifier, and this must not make it the third
 * place an account number is written down. The number lives on the QR Command page the link
 * opens, behind its own Copy button. The suite asserts no run of five digits reaches stmt/pay.js.
 *
 * A rail is a property of an account, derived and never stored (qr-command, 4 Sep 2026):
 *   qr        the account has a DuitNow payload, so its coin can be scanned or saved as an image
 *   transfer  the account names a bank, so it can be paid by DuitNow Transfer to the number
 *   jompay    the account carries a JomPAY biller code
 * A suspended account (`maintenance`) is carried with its flag so the page can leave it out.
 *
 *   node tools/paysync.mjs --sync     write stmt/pay.js from the master
 *   node tools/paysync.mjs --check    exit 1 if stmt/pay.js is not what the master produces
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(REPO, "stmt", "pay.js");
/* the same defaults qr-command's own build uses; both repos sit beside this one */
/* 08 Sep 2026: the pay master moved. pay-afif-site was retired that day and the store is
   Code\qr-command\data\accounts.json, committed in that repo; this read the retired file. */
export const PAY_MASTER = process.env.QR_MASTER || "C:/Users/maakm/Claude/Code/qr-command/data";
export const QR_REPO = process.env.QR_REPO || "C:/Users/maakm/Claude/Code/qr-command";
const WORKERS_SUBDOMAIN = "qyts8mh72kyg";

export function mastersPresent() {
  return existsSync(join(PAY_MASTER, "accounts.json")) && existsSync(join(QR_REPO, "wrangler.jsonc"));
}

/** The address of QR Command, read from its own config so a rename there cannot strand a link. */
export function paySiteUrl() {
  const cfg = readFileSync(join(QR_REPO, "wrangler.jsonc"), "utf8");
  const m = /^\s*"name"\s*:\s*"([^"]+)"/m.exec(cfg);
  if (!m) throw new Error("qr-command's wrangler.jsonc names no Worker");
  return "https://" + m[1] + "." + WORKERS_SUBDOMAIN + ".workers.dev";
}

/** What the page may know about each account: the key, the name, the bank and the rails. */
export function shipAccounts(doc) {
  return (doc.accounts || []).map((a) => ({
    key: String(a.key),
    name: String(a.name || a.key),
    bank: String(a.bank || ""),
    qr: !!a.payload,
    transfer: !!a.bank,
    jompay: !!a.biller,
    maintenance: !!a.maintenance
  }));
}

export function renderPayJs(site, accounts) {
  return "/* GENERATED by `node tools/paysync.mjs --sync`. Do not edit.\n"
    + " *\n"
    + " * The payment rails the order page may offer, read out of the pay store\n"
    + " * (Code\\qr-command\\data\\accounts.json) and QR Command's own address. Names and rails only:\n"
    + " * no account number, payload or reference is here, by design. Edit the store, then sync.\n"
    + " */\n"
    + "export const PAY_SITE = " + JSON.stringify(site) + ";\n"
    + "export const PAY_ACCOUNTS = " + JSON.stringify(accounts, null, 1) + ";\n";
}

export function payJs() {
  const doc = JSON.parse(readFileSync(join(PAY_MASTER, "accounts.json"), "utf8").replace(/^\uFEFF/, ""));
  return renderPayJs(paySiteUrl(), shipAccounts(doc));
}

async function main() {
  const check = process.argv.includes("--check");
  if (!mastersPresent()) {
    console.log("paysync: the pay master or qr-command is not on this machine; " + (check ? "nothing to check against" : "nothing written"));
    return;
  }
  const want = payJs();
  const have = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (check) {
    if (want === have) { console.log("  ok    stmt/pay.js is what the pay master produces"); return; }
    console.log("  FAIL  stmt/pay.js differs from the pay master; run: node tools/paysync.mjs --sync");
    process.exit(1);
  }
  writeFileSync(OUT, want);
  console.log("wrote " + OUT + " (" + (want.match(/"key":/g) || []).length + " accounts)");
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((e) => { console.error(String((e && e.stack) || e)); process.exit(1); });
}
