#!/usr/bin/env node
/* tools/qrsync.mjs: THE QR ENCODER, CARRIED INTO THE STATEMENTS SITE.
 *
 * The statements Worker draws a QR for each guest referral link (10 Sep 2026), and it may not
 * import one: hard rule -- nothing under stmt/ imports from src/, tools/ or a node builtin, only a
 * sibling, because that Worker must bundle alone and must never be able to reach the ledger's code
 * even by accident. Hard rule 1 forbids a second copy of anything the desk computes.
 *
 * BOTH RULES ARE KEPT THE WAY THE MASTER KEEPS THEM: this writes stmt/qr.js as engine/qr.mjs
 * VERBATIM under a generated banner, and --check fails if the two have drifted. So there is one
 * encoder and one place to edit it; stmt/qr.js is an output, like public/desk.html.
 *
 * IT INHERITS THE PROOF. engine/qr.mjs is tested in test/verify.mjs against an independent encoder;
 * a byte-identical copy is correct exactly insofar as the original is, which is the whole reason to
 * copy bytes rather than write a second encoder for the site.
 *
 * THE WORKER DRAWS THE SVG, NOT THE PAGE. The encoder is never inlined into the page's script: the
 * owner's route is server-rendered per request and the mint route returns the SVG with the link, so
 * nothing about QR drawing runs in a browser and no third-party anything is loaded.
 *
 *   node tools/qrsync.mjs --sync     write stmt/qr.js from engine/qr.mjs
 *   node tools/qrsync.mjs --check    non-zero if they differ (CI)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const SOURCE = join(REPO, "engine", "qr.mjs");
export const TARGET = join(REPO, "stmt", "qr.js");

const BANNER =
  "/* GENERATED FROM engine/qr.mjs BY tools/qrsync.mjs --sync. DO NOT EDIT THIS FILE.\n"
  + " * The statements Worker may import only a sibling, so the one encoder is carried here verbatim\n"
  + " * rather than imported or rewritten. Edit engine/qr.mjs, run the sync, and commit both; CI runs\n"
  + " * --check and fails on any drift. Everything below this banner is that file, byte for byte. */\n";

/** What stmt/qr.js should contain, given what engine/qr.mjs contains now. */
export function expected() {
  return BANNER + readFileSync(SOURCE, "utf8");
}

/** True when the shipped copy is what the source produces. */
export function matches() {
  let got = "";
  try { got = readFileSync(TARGET, "utf8"); } catch (e) { return false; }
  return got === expected();
}

function main() {
  const check = process.argv.includes("--check");
  if (!check && !process.argv.includes("--sync")) {
    console.error("usage: node tools/qrsync.mjs --sync | --check");
    process.exit(2);
  }
  if (check) {
    if (matches()) { console.log("stmt/qr.js is engine/qr.mjs, byte for byte"); return; }
    console.error("::error::stmt/qr.js has drifted from engine/qr.mjs. Run: node tools/qrsync.mjs --sync");
    process.exit(1);
  }
  writeFileSync(TARGET, expected());
  console.log("wrote stmt/qr.js from engine/qr.mjs (" + expected().length + " bytes)");
}

/* the hand-built file URL check is false on Linux and the tool then silently does nothing */
if (import.meta.url === pathToFileURL(process.argv[1] || "").href) main();
