#!/usr/bin/env node
/* tools/stmt-fonts.mjs: THE BRAND FACES, CARRIED INTO THE STATEMENTS SITE AS BYTES (22 Sep 2026).
 *
 * The site's Worker serves no files: stmt/ is code only and a Worker has no filesystem, which is
 * why its icon is bytes in stmt/icons.js. The two font files the design system keeps in fonts/
 * (vendored here as design/fonts/ by tools/designsync.mjs --pull) take the same road: base64 in
 * stmt/fonts.js, served at /fonts/<name> by stmt/worker.js with a year of cache, because a font
 * file is immutable and the page's @font-face names it by the same path on every surface.
 *
 *   node tools/stmt-fonts.mjs --sync     write stmt/fonts.js from design/fonts/
 *   node tools/stmt-fonts.mjs --check    non-zero if it would differ (the gate and CI)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const FONT_FILES = ["fraunces-latin.woff2", "jetbrains-mono-latin.woff2"];
const TARGET = join(REPO, "stmt", "fonts.js");

/** What stmt/fonts.js should contain, given design/fonts/ now. */
export function expected() {
  const entries = FONT_FILES.map((f) =>
    "  " + JSON.stringify(f) + ": " + JSON.stringify(readFileSync(join(REPO, "design", "fonts", f)).toString("base64")) + ",");
  return "/* stmt/fonts.js: GENERATED by tools/stmt-fonts.mjs --sync from design/fonts/. Never edit it; the gate\n"
    + "   and CI check it against the generator. The brand faces as bytes, because this Worker serves no files. */\n"
    + "export const FONTS = {\n" + entries.join("\n") + "\n};\n";
}

/** True when the shipped copy is what design/fonts/ produces. */
export function matches() {
  try { return readFileSync(TARGET, "utf8") === expected(); } catch (e) { return false; }
}

function main() {
  const mode = process.argv[2] || "--check";
  if (mode === "--sync") {
    writeFileSync(TARGET, expected());
    console.log("wrote stmt/fonts.js (" + FONT_FILES.length + " faces)");
  } else if (mode === "--check") {
    if (!matches()) {
      console.error("stmt/fonts.js is not what tools/stmt-fonts.mjs produces from design/fonts/.");
      console.error("Run: node tools/stmt-fonts.mjs --sync");
      process.exit(1);
    }
    console.log("stmt/fonts.js matches design/fonts/");
  } else {
    console.error("usage: node tools/stmt-fonts.mjs [--sync|--check]");
    process.exit(2);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
