/* GENERATED by `node tools/paysync.mjs --sync`. Do not edit.
 *
 * The payment rails the order page may offer, read out of the pay master
 * (Code\pay-afif-site\accounts.json) and QR Command's own address. Names and rails only:
 * no account number, payload or reference is here, by design. Edit the master, then sync.
 */
export const PAY_SITE = "https://jb3zkzyqguu5.qyts8mh72kyg.workers.dev";
export const PAY_ACCOUNTS = [
 {
  "key": "wise",
  "name": "JPMorgan Chase",
  "bank": "JPMorgan Chase Bank Berhad",
  "qr": false,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "maybank",
  "name": "Maybank",
  "bank": "Maybank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "ambank",
  "name": "AmBank",
  "bank": "AmBank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "gx",
  "name": "GX Bank",
  "bank": "GX Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "boostbank",
  "name": "Boost Bank",
  "bank": "Boost Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "aeon",
  "name": "AEON Bank",
  "bank": "AEON Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "ryt",
  "name": "Ryt Bank",
  "bank": "Ryt Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "kaf",
  "name": "KAF Digital Bank",
  "bank": "KAF Digital Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "tng",
  "name": "Touch 'n Go",
  "bank": "Touch 'n Go eWallet",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "tngbiz",
  "name": "Touch 'n Go Business",
  "bank": "Touch 'n Go eWallet",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "spay",
  "name": "ShopeePay",
  "bank": "ShopeePay",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "boostw",
  "name": "Boost",
  "bank": "Boost",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "setel",
  "name": "Setel",
  "bank": "Setel",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "instapay",
  "name": "Instapay",
  "bank": "Instapay",
  "qr": true,
  "transfer": true,
  "jompay": true,
  "maintenance": false
 }
];
