/* GENERATED by `node tools/paysync.mjs --sync`. Do not edit.
 *
 * The payment rails the order page may offer, read out of the pay store
 * (Code\qr-command\data\accounts.json) and QR Command's own address, and the one link into it.
 * Names and rails only: no account number, payload or reference is here, by design. Edit the
 * store, then sync.
 */
export const PAY_SITE = "https://jb3zkzyqguu5.qyts8mh72kyg.workers.dev";
export const PAY_ACCOUNTS = [
 {
  "key": "wise",
  "name": "JPMorgan Chase",
  "bank": "JPMorgan Chase Bank Berhad",
  "qr": false,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "maybank",
  "name": "Maybank",
  "bank": "Maybank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "ambank",
  "name": "AmBank",
  "bank": "AmBank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "gx",
  "name": "GX Bank",
  "bank": "GX Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "boostbank",
  "name": "Boost Bank",
  "bank": "Boost Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "aeon",
  "name": "AEON Bank",
  "bank": "AEON Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "ryt",
  "name": "Ryt Bank",
  "bank": "Ryt Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "kaf",
  "name": "KAF Digital Bank",
  "bank": "KAF Digital Bank",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "tng",
  "name": "Touch 'n Go",
  "bank": "Touch 'n Go eWallet",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "tngbiz",
  "name": "Touch 'n Go Business",
  "bank": "Touch 'n Go eWallet",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "spay",
  "name": "ShopeePay",
  "bank": "ShopeePay",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": true
 },
 {
  "key": "boostw",
  "name": "Boost",
  "bank": "Boost",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "setel",
  "name": "Setel",
  "bank": "Setel",
  "qr": true,
  "transfer": true,
  "jompay": false,
  "maintenance": false
 },
 {
  "key": "instapay",
  "name": "Instapay",
  "bank": "Instapay",
  "qr": true,
  "transfer": true,
  "jompay": true,
  "maintenance": false
 }
];
/** QR Command at the account, the rail and the amount, with the username as the reference; "" when the page could not open it. */
export function payHref(key, rail, amount, ref) {
  var a = null, sen = Math.round(Number(amount) * 100);
  for (var i = 0; i < PAY_ACCOUNTS.length; i++) if (PAY_ACCOUNTS[i].key === key) a = PAY_ACCOUNTS[i];
  if (!a || a.maintenance || (rail !== "qr" && rail !== "transfer") || !a[rail]) return "";
  if (!(sen > 0 && sen < 1e8) || !/^[A-Za-z0-9-]{1,20}$/.test(String(ref))) return "";
  return PAY_SITE + "/#" + [a.key, rail, (sen / 100).toFixed(2), ref].map(encodeURIComponent).join("/");
}
