/* stmt/words.js: EVERY WORD THE COUNTER SHOWS, BY KEY (S13 13.3, his decision D12 of 24 Sep 2026).
 *
 * ONE TABLE A LANGUAGE, A PLAIN OBJECT OF KEY TO WORDS. EN is complete: the page (stmt/page.js), the door, the sheets, the
 * places, the banners (stmt/sw.js) and the refusals all read it, the page's markup at first paint and its script as it
 * draws. A KEY A LANGUAGE LACKS IS ENGLISH'S, NEVER THE KEY'S NAME, so a language can be a slice (13.4).
 *
 * SLOTS, NEVER HALVES. {n} style slots carry a figure, a date, a username or a mark; a sentence is never built by joining
 * translated halves, so a language may put the slot where its grammar wants it. In markup **x** is bold, and a slot named
 * after a mark (dots, share, paste, and the rest of the page's GLYPH) is that mark, drawn by the page; {dev} is the
 * device's word (phone, computer, iPad) in the sentence's own language.
 *
 * A REFUSAL IS A CODE. Every refusal a customer can meet is EN["e.<code>"]: the Worker answers it as
 * { error: <English>, code } (refusal() below, with `vars` for its slots), and the page words the code from the table,
 * the Worker's English standing for a code the page does not know. A request only a broken page could send (a method, a
 * missing wrap) keeps its plain English and no code. The codes are listed here and nowhere else.
 *
 * WHAT IS NOT HERE: Salt Admin (stmt/owner.js), which stays English and unkeyed; the words he sends a customer
 * (stmt/send.js), which he writes himself; the sealed statement, a dated record; and his notice, which is his own words.
 *
 * THE RULES OF THE PAGE HOLD FOR EVERY LANGUAGE: no product word, no level's name, no brand and never the desk's name;
 * figures in RM and units; the suite reads both tables with the site's own lists (src/orders.js). The table travels inside
 * the page's script, spliced by function, so a $ in it is kept as typed. British English for the English only.
 */

export const EN = {
  /* ---- REFUSALS: e.<code>, what the Worker answers beside its code (stmt/worker.js, stmt/orders.js, stmt/orderbook.js) ---- */
  "e.refused": "That username and password were not accepted.",
  "e.tooMany": "Too many attempts. Try again in fifteen minutes.",
  "e.signinOrders": "Sign in again to see your orders.",
  "e.signinLinks": "Sign in again to see your links.",
  "e.signinCode": "Sign in again to make a code.",
  "e.codeOff": "Signing in with a code is not switched on here.",
  "e.linksMax": "you already have {n} links; withdraw one to make another",
  "e.mintFailed": "could not mint an unused id; try again",
  "e.busy": "Orders could not be reached just now. Try again in a minute.",
  "e.frozen": "Orders are being moved and are paused for a minute. Try again in a minute.",
  "e.placeWhere": "say roughly where it is going, so the delivery can be quoted",
  "e.openMax": "you already have {n} orders open; wait for one to be completed",
  "e.pricesMoved": "prices moved",
  "e.noOrder": "no such order",
  "e.cancelDone": "this order is complete, so it cannot be cancelled here",
  "e.cancelCancelled": "this order is cancelled, so it cannot be cancelled here",
  "e.cancelDeclined": "this order is not taken, so it cannot be cancelled here",
  "e.cancelMoved": "the goods are already with you, so this cannot be cancelled here",
  "e.cancelClaim": "we are checking the RM {rm} you sent, so this can be cancelled once we have answered it",
  "e.methodEarly": "payment is chosen once the order is confirmed",
  "e.payEarly": "payment is recorded once the order is confirmed",
  "e.payHowMuch": "say how much you paid",
  "e.paySent": "what is owed on this order is sent already and waiting for us to confirm it",
  "e.payOver": "that is more than the {rm} outstanding on this order",
  "e.payHow": "choose how you are paying first",
  "e.payCash": "cash is recorded by us when we take it, so there is nothing to send here",
  "e.sayEmpty": "write something first",
  "e.sayCap": "there are already {n} of your messages on this order",
  "e.railNone": "that is not a way to pay this site offers",
  "e.cashWithheld": "cash on handover is not offered while goods you already hold are unpaid",
  "e.railAccount": "that account does not take that rail",
  "e.tngOff": "the Touch 'n Go Business code is not available",
  "e.claimHowMuch": "say how much you sent",
  "e.claimsMax": "there are already {n} payments of yours waiting for us to confirm",
  /* ---- THE WHOLE PAGE ---- */
  "x.close": "Close",
  "dev.phone": "phone",
  "dev.computer": "computer",
  "mon3": "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec",
  "months": "January February March April May June July August September October November December",
  "day3": "Sun Mon Tue Wed Thu Fri Sat",
  "unit.one": "{n} {u}",
  "unit.many": "{n} {u}s",
  "deliv": "Delivery is charged by area. We tell you the charge when we confirm, before you pay, and you can cancel then at no cost.",
  /* ---- THE PLACES, and whose account it is ---- */
  "place.home": "Home",
  "place.prices": "Prices",
  "place.order": "Orders",
  "place.stmt": "Account",
  "place.card": "Rewards",
  "who.as": "Signed in as {u}",
  /* ---- THE DOOR ---- */
  "door.h": "Sign in",
  "door.lead": "With the username and password we sent you.",
  "door.un": "Username",
  "door.unHint": "Two groups of four, like abcd-efgh.",
  "door.pw": "Password",
  "door.show": "Show",
  "door.pwHint": "Pasting the whole message works: we keep only the password.",
  "door.rem": "Keep me signed in on this {dev}",
  "door.go": "Sign in",
  "door.again": "Try again",
  "door.toCode": "I have a sign-in code",
  "door.help": "Lost your password or your link? Ask us for a **new sign-in link**. It works straight away.",
  /* ---- OPENING, SIGNED OUT, AND ANOTHER ACCOUNT ON THIS PHONE ---- */
  "open.lead": "Opening your account...",
  "out.h": "You were signed out on this {dev}",
  "out.p": "Sign in again to carry on. What you were doing is kept.",
  "rep.yes": "Replace",
  /* ---- THE LINK PAGE, the welcome ---- */
  "link.h": "Your Salt Counter",
  "link.lead": "This link opens your account on this {dev} and keeps it signed in.",
  "link.inside": "Inside",
  "link.r1": "What you owe, and paying it",
  "link.r2": "Your prices, and ordering",
  "link.r3": "Each order, and its messages",
  "link.inappIos": "This app keeps nothing once you close it. Tap {dots} and choose to open this page in **Safari**, then tap Continue there.",
  "link.inappDroid": "This app keeps nothing once you close it. Tap {vdots} and choose to open this page in **Chrome**, then tap Continue there.",
  "link.copy": "Copy the link",
  "link.go": "Continue",
  "link.once": "The link works once. Not your {dev}? Close this page and nothing is used.",
  /* ---- SAVING IT AS AN APP: the keep card and its sheet ---- */
  "keep.h": "Keep it on your Home Screen",
  "keep.go": "Show me how",
  "keep.install": "Install Salt Counter",
  "keep.line": "One tap to open, and it stays signed in. It is saved as **Salt Counter**.",
  "keep.sam": "Tap {menu} then Add page to, then Home screen.",
  "keep.desk": "Look for the install mark {install} at the end of the address bar.",
  "keep.droid": "Tap {vdots} then Install app or Add to Home screen.",
  "keep.why": "On iPhone the Home Screen app starts signed out, so it asks once for this code. Copy it now, and paste it there.",
  "keep.s1": "Tap {dots} then {share}",
  "keep.where": "At the foot of Safari. On an older iPhone, just the second mark.",
  "keep.s2": "Tap {addsq} then Add",
  "keep.s3": "Open the new icon and tap {paste} Paste the code",
  "keep.code": "Your code",
  "code.once": "Works once, for 15 minutes.",
  "code.copy": "Copy the code",
  /* ---- ONE STEP TO FINISH: the saved app's first open, and a code from another device ---- */
  "code.h": "One step to finish",
  "code.lead": "Bring your sign-in across from Safari. You do this once on this {dev}.",
  "code.paste": "{paste} Paste the code",
  "code.or": "Or type it",
  "code.hint": "Eight letters and numbers, as Safari showed them.",
  "code.door": "Sign in with username and password",
  "code.help": "No code? Open your sign-in link in **Safari**, tap Keep it on your Home Screen, and copy the code shown there.",
  /* ---- THIS DEVICE, in Account ---- */
  "dev.h": "This device",
  "dev.out": "Sign out of this {dev}",
  "dev.another": "Sign in another device",
  "dev.scan": "On the other device, scan this with its camera to open Salt Counter, then type the code where it asks for one.",
  "dev.qrAlt": "A code that opens Salt Counter",
  "dev.qrCap": "Opens Salt Counter",
  "dev.code": "The code",
  /* ---- PAYING: the pay sheet ---- */
  "pay.h": "Pay",
  /* ---- ACCOUNT ---- */
  "acct.back": "Back to your statement",
  "acct.months": "Show one month",
  /* ---- A GUEST'S BOARD AND A SHUT LINK (no script: English, from here) ---- */
  "board.h": "Price list",
  "board.week": "For the week of {w}.",
  "board.goods": "The price is for the goods.",
  "board.ask": "Ask about any size that is not listed.",
  "board.none": "No price list has been written yet.",
  "board.only": "The only price for this product",
  "board.size": "Size",
  "board.price": "Price",
  "board.next": "To order, reply to the person who sent you this link.",
  "shut.h": "This link is not open",
  "shut.p": "Ask the person who sent it to you.",
  "shut.title": "Link not open",
  "door.hide": "Hide",
  "door.unfitUn": "A username never uses 0, 1, i, l, o or u. Check the symbols you typed.",
  "door.unfitPw": "A password never uses 0, 1, i, l, o or u. Check the symbols you typed.",
  /* ---- WHAT THE WHOLE PAGE SAYS ---- */
  "x.notSent": "Not sent. Check your connection and try again.",
  "x.checkConn": "Check your connection and try again.",
  "x.opening": "Opening...",
  "x.later": "Try again later.",
  "x.needs": "Needs you",
  "keep.hApp": "Keep it as an app",
  "keep.making": "Making your code...",
  "keep.off": "Saving it as an app is not switched on yet. Ask us, and sign in inside the new app meanwhile.",
  "keep.copied": "Copied. Now tap the marks above, then open the new icon and paste.",
  "keep.copyFail": "Copy failed. Type the code in the new app instead.",
  "code.notMade": "The code could not be made just now. Close this and open it again.",
  "code.hDoor": "Sign in with a code",
  "code.leadDoor": "Type the eight letters and numbers you were given. A code works once.",
  "code.hintDoor": "Eight letters and numbers, in two groups of four.",
  "code.dropped": "Not opened: the connection dropped. Try again; if the code is then refused, make a new one.",
  "code.nothing": "That code did not open anything. A code works once, for 15 minutes: make a new one and try again.",
  "code.inapp": "This app keeps nothing once you close it. Open this page in Safari or Chrome to sign in.",
  "code.unfit": "A code never uses 0, 1, I, L, O or U. Check the symbols you typed.",
  "code.pasteFail": "Paste did not work here. Type the code below instead.",
  "code.noClip": "There is no code on the clipboard. Copy it in Safari, or type it below.",
  "code.noClipDoor": "There is no code on the clipboard. Type it below.",
  "dev.aDevice": "A device",
  "dev.thisOne": "This one",
  "dev.kept": "Kept signed in since {a}, last used {b}.",
  "dev.visit": "Signed in {a}, for that visit.",
  "dev.yours": "Your devices",
  "dev.signinSee": "Sign in again to see them.",
  "dev.unread": "They could not be read just now.",
  "dev.outOthers": "Sign out other devices",
  "dev.outAgain": "Tap again to sign them out",
  "dev.outGoing": "Signing out...",
  "dev.outOne": "Signed out {n} other device.",
  "dev.outMany": "Signed out {n} other devices.",
  "dev.outNone": "No other device was signed in.",
  "dev.making": "Making a code...",
  "dev.off": "Signing in with a code is not switched on here yet. Ask us for a sign-in link instead.",
  "dev.copied": "Copied. Type it on the other device, where Salt Counter asks for a code.",
  "dev.copyFail": "Copy failed. Read the code across instead.",
  "rep.ask": "Replace {was} on this {dev}? It will open {u} instead.",
  "rep.askAcct": "Replace {was} on this {dev}? It will open this account instead.",
  "rep.keep": "Keep {u}",
  "lock.out": "Signed out. Sign in again when you want it.",
  "lock.owner": "Signed out. Tap an account to open it again.",
  "lapse.notSent": "Not sent: you were signed out on this {dev}. Sign in to carry on.",
  "lapse.kept": "This {dev} could not sign you back in just now.",
  "lapse.out": "You were signed out on this {dev}.",
  /* ---- HOME ---- */
  "home.welcome": "Welcome",
  "home.morning": "Good morning",
  "home.afternoon": "Good afternoon",
  "home.evening": "Good evening",
  "home.stay": ". This {dev} stays signed in.",
  /* ---- ACCOUNT, and the month filter ---- */
  "acct.nothing": "Nothing on your account yet. Your orders will show here.",
  "acct.issued": "The statement issued {d}, kept as it was sent.",
  "acct.earlier": "Earlier statements",
  "acct.keptLive": "Kept as they were sent. Your statement above keeps up with every order.",
  "acct.kept": "Kept as they were sent.",
  "acct.showing": "Showing {m}. What the account stands at, below, is the whole account.",
  "acct.all": "Showing every order from the start.",
  "acct.allPill": "All",
  "acct.now": "Now",
  /* ---- NOTIFICATIONS, on This device, the order sheet and Orders ---- */
  "push.h": "Notifications",
  "push.devIos": "Not in this browser. On an iPhone they come to the app saved on your Home Screen.",
  "push.devNo": "This browser cannot receive them.",
  "push.devOn": "On. This {dev} is told when an order changes. A reply comes too, and a payment due at 10:00 and 18:00.",
  "push.devOff": "Off. Nothing is sent to this {dev}.",
  "push.off": "Turn off",
  "push.on": "Turn on",
  "push.offFail": "They could not be turned off just now. Try again.",
  "dev.saved": "Saved as an app",
  "dev.inIt": "You are in it now.",
  /* ---- REWARDS, an associate's card ---- */
  "rew.later": "Your card is written with the next update.",
  "rew.h": "Your card",
  "rew.lead": "Your reward, what you have bought and what has gone out through you. Every month from the start; the newest opens.",
  "rew.held": "Reward: {left} to take. Held for now.",
  "rew.heldP": "Reward: {left} to take ({earned} earned, {taken} taken). Held for now.",
  "rew.ask": "Reward: {left} to take. Ask on any order to take it.",
  "rew.askP": "Reward: {left} to take ({earned} earned, {taken} taken). Ask on any order to take it.",
  "rew.none": "Reward: {left} to take.",
  "rew.noneP": "Reward: {left} to take ({earned} earned, {taken} taken).",
  "rew.next": "To your next unit",
  "rew.nextAria": "{p}% of the way to your next unit",
  "rew.bought": "You bought",
  "rew.sold": "Sold through you",
  "rew.onward": "Onward sales",
  "rew.brought": "Brought in",
  "rew.people": "People you introduced",
  "rew.noMonth": "Nothing in that month.",
  "rew.date": "Date",
  "rew.what": "What",
  "rew.through": "Through you",
  /* ---- THEIR OWN LINKS ---- */
  "lnk.open": "Open",
  "lnk.waiting": "Waiting",
  "lnk.declined": "Not approved",
  "lnk.withdrawn": "Withdrawn",
  "lnk.lineWaiting": "Shut until we approve it. Once it opens you can share it from here.",
  "lnk.lineDeclined": "We did not approve this link, so it stays shut.",
  "lnk.lineWithdrawn": "Withdrawn. Nothing opens it now.",
  "lnk.opened1": "Opened {n} time.",
  "lnk.openedN": "Opened {n} times.",
  "lnk.opened1Last": "Opened {n} time, last {d}.",
  "lnk.openedNLast": "Opened {n} times, last {d}.",
  "lnk.notOpened": "Not opened yet.",
  "lnk.h": "Your links",
  "lnk.count": "{n} of {m}",
  "lnk.reading": "Reading your links.",
  "lnk.none": "None yet. A link opens a price list for somebody you bring in, and nothing else.",
  "lnk.made": "Link made {d}",
  "lnk.yours": "Your link",
  "lnk.qrAlt": "A code that opens the price list you are sharing",
  "lnk.share": "Share",
  "lnk.notShared": "Not shared. Copy the address above instead.",
  "lnk.copy": "Copy link",
  "lnk.copied": "Copied",
  "lnk.copyFail": "Copy failed",
  "lnk.qrHide": "Hide the QR",
  "lnk.qrShow": "Show the QR",
  "lnk.withdraw": "Withdraw",
  "lnk.withdrawAsk": "Withdraw this link? Whoever holds it will not be able to open it.",
  "lnk.max": "You have {n} links. Withdraw one to make another.",
  "lnk.next": "A new link stays shut until we approve it. Once it is open it shows whoever you give it to a price list and nothing else, and you share it from here.",
  "lnk.make": "Make a link",
  "lnk.notMade": "That link was not made.",
  /* ---- PRICES ---- */
  "pr.none": "No price list has been written for your account yet. It is written with the next update and changes weekly.",
  "pr.asAt": "Prices as at {d}.",
  "pr.asAtTap": "Prices as at {d}. Tap a size to order it.",
  "pr.week": "For the week of {w}.",
  "pr.weekTap": "For the week of {w}. Tap a size to order it.",
  "pr.goods": "The price is for the goods. {deliv} The list is written from your own history and changes weekly.",
  "pr.since": "Buying with us since {m}.",
  "pr.board": "The same price for everybody.",
  "pr.rate1": "Your rate: {rm} per {u}, from your last {n} order.",
  "pr.rateN": "Your rate: {rm} per {u}, from your last {n} orders.",
  "pr.own": "Your own rate follows your first order.",
  "pr.soon": "Price coming soon.",
  "ord.opensSet": "Ordering opens once your prices are set.",
  "ord.opensList": "Ordering opens once your price list is written, with the next update.",
  /* ---- THE ORDER SHEET ---- */
  "sh.change": "Change",
  "sh.new": "New order",
  "sh.whyFor": "Say who it is for.",
  "sh.whySize": "Pick a size.",
  "sh.whyWhere": "Say roughly where it is going.",
  "sh.whereSame": "Same as last time. An area, not an address.",
  "sh.where": "An area, not an address.",
  "sh.whoFor": "Who is it for?",
  "sh.me": "Me",
  "sh.friend": "A friend",
  "sh.size": "Size",
  "sh.usual": "your usual",
  "sh.reach": "How it reaches you",
  "sh.collect": "I will collect",
  "sh.deliver": "Deliver to me",
  "sh.whereTo": "Where to",
  "sh.wherePh": "a neighbourhood or a landmark",
  "sh.note": "Note",
  "sh.notePh": "optional, a line about this order",
  "sh.addNote": "Add a note",
  "sh.plusDeliv": "and delivery, set when we confirm",
  "sh.toCollect": "to collect",
  "sh.review": "Review",
  "sh.stillAt": "Your prices were updated just now. This size is still {rm}.",
  "sh.limit": "You have {n} orders open, the most at one time. Cancel one, or wait for one to finish, and you can order again.",
  "st.partDelivered": "Part delivered",
  "st.partCollected": "Part collected",
  "sh.placed": "Placed {t}",
  "ord.cancel": "Cancel this order",
  "sh.partOwed": "Part of it is with you, so this one finishes once the rest is with you and it is paid.",
  "sh.part": "Part of it is with you, so this one finishes once the rest is with you.",
  "sh.withYou": "The goods are with you, so this one finishes when it is paid.",
  "ord.cancelAskPaid": "Cancel this order? The {rm} you paid is refunded.",
  "ord.cancelAsk": "Cancel this order?",
  "ord.notCancelled": "It could not be cancelled.",
  "sh.check": "Check your order",
  "sh.for": "For",
  "sh.price": "Price",
  "sh.how": "How",
  "sh.deliveredTo": "Delivered to {p}",
  "sh.youCollect": "You collect it",
  "sh.delivery": "Delivery",
  "sh.setOnConfirm": "Set when we confirm",
  "sh.moved": "This size is now **{now}** (was {was}). Place at {now}?",
  "sh.gone": "This size is no longer on your list. Change it to pick another.",
  "sh.placeAt": "Place at {rm}",
  "sh.place": "Place order",
  "sh.notPlaced": "The order was not placed.",
  "sh.sent": "Order sent",
  "sh.sentP": "It is under Your orders now. We confirm it there, and you pay once it is confirmed.",
  "sh.buzzOn": "On. This {dev} is told when it is confirmed.",
  "sh.buzzQ": "A buzz when it is confirmed?",
  "sh.buzzNo": "This browser cannot give notifications. On an iPhone, add this page to the Home Screen from the Share menu and open it from there.",
  "sh.buzzOnly": "Only for your orders and your payments.",
  "sh.buzzYes": "Turn on notifications",
  "sh.buzzNot": "Not now",
  "sh.see": "See the order",
  /* ---- ORDERS ---- */
  "ord.due": "Payment due",
  "ord.view": "Read only: their orders as their own page shows them. Nothing here is placed, paid or sent.",
  "pay.overdue": "Overdue",
  "pay.hold": "Please pay the overdue amount of {rm} before placing another order.",
  "pay.payRm": "Pay {rm}",
  "ord.holdP": "Ordering opens again as soon as you tell us it is sent, and your prices stay open meanwhile. Each order the amount is made of is on your statement.",
  "ord.seeStmt": "See your statement",
  "ord.lead": "Pick a size and check it over before you place it. Once we confirm it you can pay, and you are told when the goods are on their way.",
  "push.no": "This browser cannot receive notifications. On an iPhone, add this page to the Home Screen from the Share menu and open it from there; otherwise keep the page open and it checks every ten seconds.",
  "push.onAll": "On. You will be told when your order changes, when there is a reply, and at 10:00 and 18:00 when a payment is due.",
  "push.ask": "Be told on this {dev} when your order changes, when there is a reply, and at 10:00 and 18:00 when a payment is due. The banner says only what kind of news it is, never an amount or which order, and a tap opens the order.",
  "push.notify": "Notify me on this {dev}",
  /* ---- WHERE AN ORDER IS, in the customer's words ---- */
  "st.placed": "Sent",
  "st.acknowledged": "Confirmed",
  "st.ready": "Ready",
  "st.readyDeliver": "Ready to deliver",
  "st.readyCollect": "Ready to collect",
  "st.done": "Complete",
  "st.declined": "Not taken",
  "st.cancelledUs": "Cancelled by us",
  "st.cancelledYou": "Cancelled by you",
  "st.delivered": "Delivered",
  "st.collected": "Collected",
  /* ---- WHAT HAPPENED, a line a step; {m} is the way paid ---- */
  "hist.paid": "You paid {rm}",
  "hist.paidBy": "You paid {rm} by {m}",
  "hist.sent": "You sent {rm}, waiting for us to confirm it",
  "hist.sentBy": "You sent {rm} by {m}, waiting for us to confirm it",
  "hist.received": "We received {rm}",
  "hist.notFound": "We have not found {rm} yet",
  "hist.recorded": "We recorded a payment of {rm}",
  "hist.cash": "We received {rm} in cash",
  "hist.closed": "Closed at {a} of the {b} ordered",
  "hist.delivered": "{a} delivered",
  "hist.collected": "{a} collected",
  "hist.chose": "You chose to pay",
  "hist.choseBy": "You chose to pay by {m}",
  "hist.withNote": "{s}: {n}",
  /* ---- WHY AN ORDER IS UNDER NEEDS YOU, a list ---- */
  "why.toPay": "{rm} to pay",
  "why.sent": "{rm} sent, waiting for us to confirm",
  "why.lost": "a payment we have not found",
  "why.reply": "a reply for you",
  "why.placed": "waiting to be confirmed",
  "ord.noneYet": "None yet.",
  "ord.open": "Open",
  "ord.earlier1": "{n} earlier order",
  "ord.earlierN": "{n} earlier orders",
  /* ---- AN ORDER'S OWN SCREEN ---- */
  "oh.deliverTo": "Ordered {t}, to be delivered to {p}",
  "oh.deliverToF": "Ordered {t}, to be delivered to {p}, on behalf of a friend",
  "oh.deliver": "Ordered {t}, to be delivered",
  "oh.deliverF": "Ordered {t}, to be delivered, on behalf of a friend",
  "oh.collect": "Ordered {t}, to collect",
  "oh.collectF": "Ordered {t}, to collect, on behalf of a friend",
  "oh.steps": "Where the goods are",
  "ow.refunded": "The {rm} you paid is refunded.",
  "ow.nothingOwed": "Nothing is owed.",
  "ow.placed": "Waiting to be confirmed. You will see it change here.",
  "ow.done": "Your order is now complete. Thank you for your loyalty.",
  "ow.declined": "Not taken.",
  "ow.declinedWhy": "Not taken: {why}.",
  "ow.cancelUs": "Cancelled by us.",
  "ow.cancelUsWhy": "Cancelled by us: {why}.",
  "ow.cancelledPaid": "Cancelled. The {rm} you paid is refunded.",
  "ow.cancelled": "Cancelled before anything moved. Nothing is owed.",
  "ow.deliveredOn": "Delivered on **{d}**.",
  "ow.collectedOn": "Collected on **{d}**.",
  "ow.partDeliveredOn": "{a} of {b} delivered on **{d}**.",
  "ow.partCollectedOn": "{a} of {b} collected on **{d}**.",
  "ow.dayWent": "the day it went",
  "ow.readyDeliver": "Ready to deliver, since **{d}**.",
  "ow.readyCollect": "Ready to collect, since **{d}**.",
  "ow.confirmed": "Confirmed on **{d}**, and being prepared.",
  "ow.closed": "Closed at {a} of the {b} ordered, {rm} for the goods.",
  "pw.WithYou": "The goods are with you",
  "pw.Part": "Part of the goods is with you",
  "pw.CashArrives": "In cash when it arrives",
  "pw.CashCollect": "In cash when you collect",
  "pw.NowArrives": "Now, or when it arrives",
  "pw.NowCollect": "Now, or when you collect",
  "om.to": "To {p}",
  "om.goods": "Goods",
  "om.handed": "{a} handed over of the {b} ordered",
  "om.set": "Set when we confirm the order",
  "om.setToP": "To {p}. Set when we confirm the order",
  "om.paid": "Paid",
  "om.sentByYou": "Sent by you",
  "om.waiting": "Waiting for us to confirm",
  "om.sentAcct": "Sent against your account",
  "om.received": "Received. Your statement shows it at its next update",
  "om.notFound": "Not found yet",
  "om.checkBank": "Check it left your bank, then pay it again",
  "pay.still": "Still to pay",
  "om.sentWaiting": "Sent, waiting for us to confirm",
  "om.paidFull": "Paid in full",
  /* ---- THE MESSAGES on an order ---- */
  "msg.new": "New",
  "msg.sending": "Sending",
  "msg.sent": "Sent",
  "msg.failed": "Not sent",
  "msg.h": "Messages",
  "msg.aria": "Messages on this order",
  "msg.reply": "Reply, {t}",
  "msg.you": "You, {t}",
  "msg.retry": "Tap to try again",
  "msg.ph": "Write about this order",
  "msg.send": "Send",
  "msg.notSent": "It was not sent.",
  "oh.hist": "What happened, step by step",
  "of.moved": "The goods are with you, so this can no longer be cancelled here.",
  "of.checking": "We are checking the {rm} you sent. You can cancel once we have answered it.",
  "oh.aria": "Your order of {a}, {d}",
  "ord.yours": "Your orders",
  /* ---- WHEN A PART IS DUE, and the parts, {mark} their mark ---- */
  "due.Late": "It was due by {d}.",
  "due.firstLate": "The first was due by {d}.",
  "due.Today": "Due today, {d}.",
  "due.firstToday": "The first is due today, {d}.",
  "due.Tomorrow": "Due by {d}, tomorrow.",
  "due.firstTomorrow": "The first is due by {d}, tomorrow.",
  "due.InN": "Due by {d}, in {n} days.",
  "due.firstInN": "The first is due by {d}, in {n} days.",
  "part.Got": "{mark} {u} you received {d}",
  "part.GotF": "{mark} {u} on behalf of a friend you received {d}",
  "part.restGot": "The rest of {mark} {u} you received {d}",
  "part.restGotF": "The rest of {mark} {u} on behalf of a friend you received {d}",
  "part.Ordered": "{mark} {u}, ordered {d}",
  "part.OrderedF": "{mark} {u} on behalf of a friend, ordered {d}",
  "part.restOrdered": "The rest of {mark} {u}, ordered {d}",
  "part.restOrderedF": "The rest of {mark} {u} on behalf of a friend, ordered {d}",
  "part.Bare": "{mark} {u}",
  "part.BareF": "{mark} {u} on behalf of a friend",
  "part.restBare": "The rest of {mark} {u}",
  "part.restBareF": "The rest of {mark} {u} on behalf of a friend",
  "pay.odMany": "{n} orders past the day they were due.",
  "pay.nowMany": "{n} orders you have received.",
  "cl.waiting": "{rm} sent, waiting for us to confirm.",
  "cl.received": "{rm} received on {d}. Your statement shows it at its next update.",
  "cl.notFound": "We have not found the {rm} you sent on {d}. Check it left your bank, then pay it again.",
  /* ---- TO PAY NOW, and the pay sheet ---- */
  "pay.now": "To pay now",
  "pay.toPay": "To pay",
  "pay.nothing": "Nothing to pay now.",
  "pay.cod": "cash on handover",
  "pay.mTo": "{m} to {a}",
  "pn.ordered": "{mark} {u}, ordered {d}.",
  "pn.orderedWithYou": "{mark} {u}, ordered {d}. The goods are with you.",
  "pay.transfer": "Transfer to an account",
  "pay.scan": "Scan a code",
  "pay.scanDetail": "DuitNow QR, any bank or e-wallet",
  "pay.cashArrives": "Cash when it arrives",
  "pay.cashCollect": "Cash when you collect",
  "pay.cashOff": "Not offered while goods you already have are unpaid. Pay for those first and it comes back.",
  "pay.cashOn": "Paid to us at the handover. We record it when we take it.",
  "pay.cashGoArrives": "Pay in cash when it arrives",
  "pay.cashGoCollect": "Pay in cash when I collect",
  "pay.notChosen": "The choice was not recorded.",
  "pay.cashSaidArrives": "You pay in cash when it arrives. We record it when we take it.",
  "pay.cashSaidCollect": "You pay in cash when you collect. We record it when we take it.",
  "pay.all": "All, {rm}",
  "pay.part": "Part of it",
  "pay.amtAria": "How much you are paying, in ringgit",
  "pay.upTo": "Up to {rm}. The rest stays here to pay.",
  "pay.how": "How you pay",
  "pay.fromApp": "From your banking app, to {a}",
  "pay.fromAppAny": "From your banking app, to one of our accounts",
  "pay.into": "Pay into",
  "pay.ref": "Reference",
  "pay.refHint": "Put this in the reference, so we can match it.",
  "pay.refCopy": "Copy the reference",
  "pay.copied": "Copied.",
  "pay.copyFail": "Copy failed. Press and hold the reference instead.",
  "pay.showCode": "Show the code",
  "pay.showAcct": "Show the account number",
  "pay.cashCap": "We record it when we take it, so there is nothing to tell us afterwards.",
  "pay.opensCode": "Opens our payment page with the code. Come back here after paying.",
  "pay.opensAcct": "Opens our payment page with the account number. Come back here after paying.",
  "pay.sayHowMuch": "Say how much you are paying, up to {rm}.",
  "pay.chooseHow": "Choose how you are paying.",
  "pay.chooseAcct": "Choose which of our accounts to pay into.",
  "pay.did": "Did you send {rm}?",
  "pay.byScan": "By scanning the {a} code, reference {u}.",
  "pay.byTransfer": "By transfer to {a}, reference {u}.",
  "pay.tell": "Tell us only once it has gone from your bank. It shows as **sent, waiting** until we confirm it arrived, and we tell you either way.",
  "pay.againCode": "Show the code again",
  "pay.againAcct": "Show the account number again",
  "pay.notYet": "Not yet",
  "pay.yes": "Yes, I sent {rm}",
  "pay.notRecorded": "That was not recorded. Try again.",
  "pay.claimed": "Sent, waiting for us to confirm. We tell you when it arrives.",
  /* ---- HOME: Needs you, Coming up, Order again ---- */
  "hn.reply": "A reply: {t}",
  "hn.owing": "{rm} to pay, the goods are with you",
  "hn.ready": "Ready to collect, since {d}",
  "hc.h": "Coming up",
  "hc.placed": "Waiting to be confirmed",
  "hc.paid": "Paid",
  "hc.stillWithYou": "{rm} still to pay, the goods are with you",
  "hc.stillPart": "{rm} still to pay, part of the goods is with you",
  "hc.stillCashArrives": "{rm} still to pay, in cash when it arrives",
  "hc.stillCashCollect": "{rm} still to pay, in cash when you collect",
  "hc.stillNowArrives": "{rm} still to pay, now or when it arrives",
  "hc.stillNowCollect": "{rm} still to pay, now or when you collect",
  "hc.sent": "{rm} sent, waiting for us to confirm",
  "hc.dueOnReceipt": "Due when you receive it",
  "hc.dueOnReceiptF": "On behalf of a friend. Due when you receive it",
  "ha.again": "Order again",
  "ha.first": "Start your first order",
  "ha.start": "Start an order",
  "ha.deliv": "{rm}, delivered to {p}",
  "ha.delivF": "{rm}, delivered to {p}, for a friend",
  "ha.coll": "{rm}, collected",
  "ha.collF": "{rm}, collected, for a friend",
  "ha.all": "See all prices",
  "push.siteOff": "Notifications are not switched on for this site yet.",
  "push.denied": "Permission was not given, so nothing will be sent.",
  "push.notRecorded": "The subscription was not recorded.",
  "push.fail": "Notifications could not be switched on here. Try again later.",
  /* ---- THE DOOR's answers ---- */
  "door.needUn": "Enter your username: two groups of four.",
  "door.needPw": "Enter the password sent to you.",
  "door.checking": "Checking...",
  "door.offline": "No connection. Try again in a moment.",
  "door.tooMany": "Too many attempts. Try again later.",
  "door.noMaster": "This account was issued without the master key. Open it with the customer's own password.",
  "door.noKey": "This account has no key to open it with. Ask for it to be re-issued.",
  "door.noOpen": "That password did not open the statement.",
  "door.noRead": "The statement could not be read. Ask for it to be re-issued.",
  "door.kept": "Your account could not be opened just now. This {dev} is still remembered: try again in a moment.",
  "link.goHere": "Continue here instead",
  "link.checking": "Checking the link...",
  "link.leadU": "This link opens account {u} on this {dev} and keeps it signed in.",
  "link.copied": "Copied. Paste it into Safari or Chrome.",
  "link.copyFail": "Copy failed. Press and hold the address instead.",
  "link.lost": "Not opened: the answer did not arrive. Tap Continue again. For two minutes this page can still open it.",
  "link.spent": "That link has been used already, or it has expired. Sign in with your username and password, or ask us for a new sign-in link.",
  /* ---- THE BANNER (stmt/sw.js): the kind of news, never an amount, a product, an order or a name ---- */
  "news.confirmed": "Your order is confirmed",
  "news.ready": "Your order is ready",
  "news.reply": "A reply on your order",
  "news.paid": "Payment received",
  "news.notfound": "Payment not found yet",
  "news.due": "A payment is due",
  "news.delivered": "Your order was delivered",
  "news.collected": "Your order was collected",
  "news.part-delivered": "Part of your order was delivered",
  "news.part-collected": "Part of your order was collected",
  "news.complete": "Your order is complete",
  "news.declined": "Your order could not be taken",
  "news.cancelled": "Your order was cancelled",
  "news.tap": "Tap to open it.",
  "news.open": "Open the page to read it.",
  "news.order": "Your order",
  "news.update": "Your order has an update. Open your statement page to see it.",
  /*@@EN@@*/
};

/* S13 13.4: THE FIRST MALAY SLICE */
export const MS = {
  /*@@MS@@*/
};

export const WORDS = { en: EN, ms: MS };

/** A key's words with its slots filled. A slot's value may be a function of the language the words were found in (a date
 *  says its month in that language). A slot not given stays as written, so a missing one shows rather than vanishes. */
export function fill(w, s, L) {
  return String(w == null ? "" : w).replace(/[{]([A-Za-z0-9]+)[}]/g, function (m, k) {
    var v = s ? s[k] : undefined;
    if (typeof v === "function") v = v(L);
    return v == null ? m : String(v);
  });
}
/** The same, as markup: the words escaped, **x** bold, and each slot's value put in as markup, which the caller escapes. */
export function fillHtml(w, s, L) {
  var e = String(w == null ? "" : w).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]; });
  return fill(e.replace(/[*][*]([^*]+)[*][*]/g, function (m, b) { return "<b>" + b + "</b>"; }), s, L);
}
/** A size in words, from a language's two forms: {n} {u} at one and under, and above one; a unit already plural is kept. */
export function unitsIn(one, many, q, u) {
  u = u || "unit";
  return +q > 1 && u.slice(-1) === "s" ? q + " " + u : fill(+q > 1 ? many : one, { n: q, u: u });
}

/** A refusal a customer can meet: its English and its code, and its slots where it has any, for the page to word. */
export function refusal(code, vars) {
  const w = EN["e." + code];
  if (w == null) throw new Error("no English for the refusal " + code);
  return vars ? { error: fill(w, vars, "en"), code, vars } : { error: w, code };
}
